name: UiPath CI/CD Pipeline
 
on:
  push:
    branches:
      - main
 
jobs:
  build-and-deploy:
    runs-on: windows-latest
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
 
    - name: Set up PowerShell
      uses: actions/setup-powershell@v2
 
    - name: Install UiPath CLI
      run: |
        Invoke-WebRequest -Uri https://download.uipath.com/UiPathStudio.msi -OutFile UiPathStudio.msi
        Start-Process msiexec.exe -ArgumentList '/i UiPathStudio.msi /quiet /norestart' -NoNewWindow -Wait
 
    - name: Run Pack and Deploy Script
      run: |
        ./pack-and-deploy.ps1
      env:
        UIPATH_ORCHESTRATOR_URL: ${{ secrets.ORCHESTRATOR_URL }}
        UIPATH_ORCHESTRATOR_API_KEY: ${{ secrets.UIPATHUSERKEY }}
        UIPATH_ORCHESTRATOR_TENANT: ${{ secrets.TENANT_NAME }}
        UIPATH_ORCHESTRATOR_FOLDER: "Shared"
        UIPATH_PROJECT_PATH: "."
        OUTPUT_FOLDER: "./output"
        UIPATH_PACKAGE_NAME: "Test_GitHubActions"
