name: Pack and Publish UiPath Project to Orchestrator
 
on:
  push:
    branches:
      - main
 
jobs:
  pack-and-publish:
    runs-on: windows-latest
 
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
 
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1
 
    - name: Install UiPath
      run: |
        choco install uipath-studio -y
        choco install nuget.commandline -y
 
    - name: Pack and Publish UiPath Project to Orchestrator
      run: |
        .\scripts\pack_publish_to_orchestrator.ps1 -projectPath "$env:GITHUB_WORKSPACE" -outputPath "$env:GITHUB_WORKSPACE\output" -orchestratorUrl ${{ secrets.ORCHESTRATOR_URL }} -tenantName ${{ secrets.TENANT_NAME }} -usernameOrEmailAddress ${{ secrets.ORCHESTRATOR_USERNAME }} -password ${{ secrets.ORCHESTRATOR_PASSWORD }} -modernFolderName ${{ secrets.MODERN_FOLDER_NAME }}
      shell: pwsh
