name: Deploy workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
 PROJECT_NAME: Test_GitHubActions 
 ORCH_FOLDER: Shared
 ORCH_URL: ${{ secrets.ORCHESTRATOR_URL }}
 ORCH_TENANT: ${{ secrets.TENANT_NAME }}
 ORCH_CLIENT_ID: ${{ secrets.UIPATHCLIENTID }}
 ORCH_USER_KEY: ${{ secrets.UIPATHUSERKEY }}
 ORCH_ACC_NAME: ${{ secrets.UIPATHACCOUNTNAME }}
 CLI_URL: https://uipath.visualstudio.com/Public.Feeds/_artifacts/feed/UiPath-Official/NuGet/UiPath.CLI.Windows/overview/23.10.8894.39673

jobs:
 print-details:
    runs-on: ubuntu-latest
    steps:
      - name: echo-default-env-variables
        run: |
          echo "Home: ${HOME}"
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "GITHUB_Token: ${{ secrets.TOKEN_GITHUB }}"
 cleaner:
    runs-on: ubuntu-latest
    steps:
      - name: Runner workspace path
        run: |
          echo "Cleaning up previous run"
          rm -rf "${{ github.workspace }}"
 update_version:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
 
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
 
    - name: Update UiPath project version
      id: update_version
      run: |
        project_file='project.json'
        
        python - <<EOF
        import json
 
        def increment_version(version):
            major, minor, patch = map(int, version.split('.'))
            patch += 1
            if patch >= 10:  # you can change this to control overflow
                patch = 0
                minor += 1
            if minor >= 10:
                minor = 0
                major += 1
            return f"{major}.{minor}.{patch}"
 
        # Load the project.json file
        with open('${project_file}', 'r') as file:
            data = json.load(file)
        
        # Increment the version number
        current_version = data.get('projectVersion', '0.0.0')
        new_version = increment_version(current_version)
        data['projectVersion'] = new_version
        
        # Write the changes back to project.json
        with open('${project_file}', 'w') as file:
            json.dump(data, file, indent=4)
 
        print(f"New version: {new_version}")
        EOF
 
    - name: Commit changes
      run: |
        git config --global user.name 'RamaDevi37'
        git config --global user.email 'ramadevi37@users.noreply.github.com'
        git add project.json
        git commit -m "Increment UiPath project version"
        git push 

    - name: Debug Info
      run: |
       git remote -v
       git status
       cat .git/config



        
 
