name: Update Version Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
 cleaner:
    runs-on: ubuntu-latest
    steps:
      - name: Runner workspace path
        run: |
          echo "Cleaning up previous run"
          rm -rf "${{ github.workspace }}"
 update_version:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
 
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
 
    - name: Update UiPath project version
      id: update_version
      run: |
        project_file='project.json'
        
        python - <<EOF
        import json
 
        def increment_version(version):
            major, minor, patch = map(int, version.split('.'))
            patch += 1
            if patch >= 10:  # you can change this to control overflow
                patch = 0
                minor += 1
            if minor >= 10:
                minor = 0
                major += 1
            return f"{major}.{minor}.{patch}"
 
        # Load the project.json file
        with open('${project_file}', 'r') as file:
            data = json.load(file)
        
        # Increment the version number
        current_version = data.get('projectVersion', '0.0.0')
        new_version = increment_version(current_version)
        data['projectVersion'] = new_version
        
        # Write the changes back to project.json
        with open('${project_file}', 'w') as file:
            json.dump(data, file, indent=4)
 
        print(f"New version: {new_version}")
        EOF
 
    - name: Commit changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add project.json
        git commit -m "Increment UiPath project version"
        git push 

 
